import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import VideoPlayer from '../components/video-player'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <VideoPlayer src="http://pablo-tv-streamer.brazilsouth.azurecontainer.io:8080/memfs/1dca41df-1807-4e1f-af55-f591ac0387a9.m3u8" />
      </main>
    </>
  )
}
